version: '3.9'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=userdb
      - POSTGRES_PASSWORD=Aa123456!
      - POSTGRES_DB=movies
    ports:
      - '5432:5432'
